import {getActivePlayerSession,requireSession} from "../../../shared/js/player-session.js";
import {QuestionDeck,createQuizController} from "../../../shared/js/game-quiz.js";
const $=selector=>document.querySelector(selector);const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const configs={santai:{time:150,balance:100,maxGap:2200,step:2.8,decay:.35,obstacles:[30,60,85],label:"Santai"},normal:{time:120,balance:100,maxGap:1500,step:2.35,decay:.55,obstacles:[18,35,54,73,90],label:"Normal"},ahli:{time:95,balance:85,maxGap:1050,step:2.05,decay:.8,obstacles:[14,27,41,55,69,82,94],label:"Ahli"}};
const checkpoints=[20,40,60,80];
const state={session:null,config:null,distance:0,balance:100,timeLeft:120,score:0,lastSide:null,lastStepAt:0,highStep:false,obstacles:[],asked:new Set(),quizCorrect:0,quizTotal:0,active:0,locked:true,finished:false,timer:null,startAt:0,deck:null,quiz:null,id:crypto.randomUUID(),steps:[0,0],collisions:0};
function names(){const p=state.session?.players||["Pemain 1"];return [p[0]||"Pemain 1",state.session?.mode==="coop"?(p[1]||"Pemain 2"):p[0]||"Pemain 1"]}
function setMessage(text,type=""){$('[data-message]').textContent=text;$('[data-message]').className=`game-message ${type}`.trim()}
function renderTrack(){const obstacles=$('[data-obstacles]');obstacles.innerHTML=state.obstacles.map(item=>`<span class="egrang-obstacle ${item.cleared?"cleared":""}" style="left:${5+item.at*.9}%" title="Rintangan ${item.at} meter"></span>`).join("");$('[data-checkpoints]').innerHTML=checkpoints.map(at=>`<span class="egrang-checkpoint" data-label="${at} m" style="left:${5+at*.9}%"></span>`).join("")}
function render(){const playerNames=names();$('[data-active-player]').textContent=playerNames[state.active];$('[data-distance]').textContent=`${Math.min(100,Math.floor(state.distance))} m`;$('[data-balance]').textContent=`${Math.max(0,Math.round(state.balance))}%`;$('[data-time]').textContent=`${state.timeLeft} dtk`;$('[data-score]').textContent=state.score.toLocaleString("id-ID");$('[data-quiz-score]').textContent=`${state.quizCorrect}/${state.quizTotal}`;$('[data-balance-bar]').style.width=`${Math.max(0,state.balance)}%`;$('[data-runner]').style.left=`${5+Math.min(100,state.distance)*.9}%`;renderTrack()}
function switchRelayIfNeeded(){if(state.session.mode==="coop"&&state.distance>=50&&state.active===0){state.active=1;state.lastSide=null;setMessage(`Tongkat estafet berpindah ke ${names()[1]}.`,"success")}}
function nextObstacle(){return state.obstacles.find(item=>!item.cleared&&item.at-state.distance<=3&&item.at>=state.distance-1)}
async function step(side){if(state.locked||state.finished)return;const now=performance.now();const gap=state.lastStepAt?now-state.lastStepAt:800;state.lastStepAt=now;const button=$(`[data-step="${side}"]`);button.classList.add("active");window.setTimeout(()=>button.classList.remove("active"),150);if(side===state.lastSide){state.balance-=13;state.distance+=.35;state.collisions++;setMessage("Langkah harus bergantian. Keseimbangan berkurang.","error")}else{let gain=state.config.step;if(gap<180){state.balance-=6;gain*=.55;setMessage("Terlalu cepat. Atur ritme langkah.","warning")}else if(gap>state.config.maxGap){state.balance-=8;gain*=.7;setMessage("Terlalu lama berhenti. Jaga ritme.","warning")}else{state.balance=Math.min(100,state.balance+1.5);setMessage(`${side==="left"?"Kiri":"Kanan"} tepat. Lanjutkan bergantian.`,"success")}const obstacle=nextObstacle();if(obstacle){if(state.highStep){obstacle.cleared=true;gain+=1.2;state.score+=120;setMessage("Rintangan dilewati dengan Langkah Tinggi! +120 poin.","success")}else{state.balance-=24;gain=.25;state.collisions++;setMessage("Menabrak rintangan. Gunakan Langkah Tinggi sebelum melangkah.","error")}}state.distance=Math.min(100,state.distance+gain);state.score+=Math.round(gain*18);state.steps[state.active]++}state.lastSide=side;state.highStep=false;$('[data-high-step]').classList.remove("active");$('[data-runner]').classList.toggle("step-left",side==="left");$('[data-runner]').classList.toggle("step-right",side==="right");switchRelayIfNeeded();render();await checkQuiz();if(state.distance>=100||state.balance<=0)finish()}
function armHighStep(){if(state.locked||state.finished)return;state.highStep=!state.highStep;$('[data-high-step]').classList.toggle("active",state.highStep);setMessage(state.highStep?"Langkah Tinggi aktif untuk langkah berikutnya.":"Langkah Tinggi dibatalkan.","warning")}
async function checkQuiz(){for(const checkpoint of checkpoints){if(state.distance>=checkpoint&&!state.asked.has(checkpoint)){state.asked.add(checkpoint);state.locked=true;const question=state.deck.next();const answer=await state.quiz.ask(question,{playerName:names()[state.active],heading:`Pos ${checkpoint} Meter`});state.quizTotal++;state.deck.record(question,answer.correct);if(answer.correct){state.quizCorrect++;state.score+=300;state.balance=Math.min(100,state.balance+18);setMessage("Jawaban benar. +300 poin dan keseimbangan pulih.","success")}else{state.balance=Math.max(0,state.balance-10);setMessage("Jawaban belum tepat. Keseimbangan berkurang 10%.","warning")}state.locked=false;render();break}}}
async function countdown(){const el=$('[data-countdown]');el.hidden=false;for(const value of [3,2,1]){el.textContent=value;await sleep(750)}el.textContent="MULAI";await sleep(500);el.hidden=true}
function finish(){if(state.finished)return;state.finished=true;state.locked=true;clearInterval(state.timer);const won=state.distance>=100&&state.balance>0&&state.timeLeft>0;const duration=Math.max(1,Math.round((Date.now()-state.startAt)/1000));const finalScore=Math.min(10000,Math.round(state.score+Math.max(0,state.balance)*10+state.timeLeft*5+(won?1200:0)));$('[data-game]').hidden=true;$('[data-result]').hidden=false;$('[data-result-icon]').textContent=won?"🏆":"🎋";$('[data-result-title]').textContent=won?"Lintasan 100 meter selesai!":"Egrang kehilangan keseimbangan";$('[data-result-copy]').textContent=`${Math.floor(state.distance)} meter · ${state.quizCorrect}/${state.quizTotal} soal benar · ${state.collisions} kesalahan ritme/rintangan.`;$('[data-final-distance]').textContent=`${Math.floor(state.distance)} m`;$('[data-final-balance]').textContent=`${Math.max(0,Math.round(state.balance))}%`;$('[data-final-score]').textContent=finalScore.toLocaleString("id-ID");window.dispatchEvent(new CustomEvent("ppn:game-finished",{detail:{gameSlug:"egrang-nusantara",score:finalScore,accuracy:state.quizTotal?Math.round(state.quizCorrect/state.quizTotal*100):100,result:won?"won":"lost",mode:state.session.mode,difficulty:state.session.difficulty,levelId:"lintasan-100",durationSeconds:duration,correctCount:state.quizCorrect,questionCount:state.quizTotal,metadata:{clientSessionId:state.id,gameVersion:"2.2.0",distance:Math.floor(state.distance),balance:Math.round(state.balance),collisions:state.collisions,playerSteps:state.steps,report:state.deck.getReport(),questionSet:state.deck.getSetInfo().name}}}))}
async function start(){try{state.session=requireSession("egrang-nusantara")||getActivePlayerSession();if(!state.session)return;state.config=configs[state.session.difficulty]||configs.normal;state.balance=state.config.balance;state.timeLeft=state.config.time;state.obstacles=state.config.obstacles.map(at=>({at,cleared:false}));state.deck=await new QuestionDeck("egrang-nusantara", "data/questions.json").load();state.quiz=createQuizController($('[data-quiz-modal]'));$('[data-intro]').hidden=true;$('[data-game]').hidden=false;render();await countdown();state.startAt=Date.now();state.locked=false;setMessage(`${names()[0]} mulai. Tekan kiri dan kanan bergantian.`);state.timer=setInterval(()=>{if(state.finished||state.locked)return;state.timeLeft=Math.max(0,state.timeLeft-1);state.balance=Math.max(0,state.balance-state.config.decay);render();if(state.timeLeft<=0||state.balance<=0)finish()},1000)}catch(error){$('[data-start-error]').textContent=error.message}}
document.addEventListener("DOMContentLoaded",()=>{$('[data-start]').addEventListener("click",start);document.querySelectorAll('[data-step]').forEach(button=>button.addEventListener("pointerdown",()=>step(button.dataset.step)));$('[data-high-step]').addEventListener("pointerdown",armHighStep);window.addEventListener("keydown",event=>{if(["a","A","ArrowLeft"].includes(event.key))step("left");if(["d","D","ArrowRight"].includes(event.key))step("right");if([" ","ArrowUp","w","W"].includes(event.key)){event.preventDefault();armHighStep()}});if("serviceWorker" in navigator)navigator.serviceWorker.register("../../service-worker.js",{scope:"../../"}).catch(console.warn)});
