import {getActivePlayerSession,requireSession} from "../../../shared/js/player-session.js";
import {loadQuestionBank,selectQuestionsWithoutRepeat} from "../../../shared/js/game-quiz.js";
const $=selector=>document.querySelector(selector);const REGIONS=["Sumatra","Jawa & Bali","Kalimantan","Sulawesi","Papua & Nusa Tenggara"];const configs={santai:{time:240,lives:5,target:10,label:"Santai"},normal:{time:180,lives:4,target:12,label:"Normal"},ahli:{time:150,lives:3,target:14,label:"Ahli"}};
const state={session:null,config:null,questions:[],index:0,score:0,lives:4,correct:0,answered:0,timeLeft:180,combo:0,bestCombo:0,locked:false,finished:false,timer:null,startAt:0,id:crypto.randomUUID(),playerCorrect:[0,0],categories:{}};
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function escapeHtml(value=""){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]))}
function names(){const players=state.session?.players||["Pemain 1"];return [players[0]||"Pemain 1",state.session?.mode==="coop"?(players[1]||"Pemain 2"):players[0]||"Pemain 1"]}
function activeIndex(){return state.session.mode==="coop"?state.index%2:0}
function regionIndex(){return Math.min(4,Math.floor(state.index/3))}
function renderMap(){const current=regionIndex();$('[data-map]').innerHTML=REGIONS.map((name,index)=>`<div class="expedition-stop ${index<current?"done":index===current&&!state.finished?"active":""}"><span>${index<current?"✓":index+1}</span><strong>${name}</strong></div>`).join("")}
function renderHud(){const playerNames=names(),active=activeIndex();$('[data-active-player]').textContent=playerNames[active];$('[data-score]').textContent=state.score.toLocaleString("id-ID");$('[data-lives]').textContent=`${state.lives} ♥`;$('[data-time]').textContent=`${state.timeLeft} dtk`;$('[data-progress]').textContent=`${Math.min(state.index+1,15)}/15`;$('[data-combo]').textContent=`${state.combo}×`;$('[data-progress-bar]').style.width=`${Math.round(state.index/15*100)}%`;document.querySelectorAll('[data-player-pill]').forEach((pill,index)=>{pill.textContent=playerNames[index];pill.hidden=index===1&&state.session.mode!=="coop";pill.classList.toggle("active",index===active)});renderMap()}
async function load(){const bank=await loadQuestionBank("jelajah-nusantara","data/questions.json");const selected=await selectQuestionsWithoutRepeat("jelajah-nusantara",bank,15);state.questions=selected.map(question=>({...question,options:shuffle(question.choices.map((text,sourceIndex)=>({text,sourceIndex})))}));state.questionSetName=bank.setName}
function renderQuestion(){if(state.finished)return;if(state.index>=15||state.lives<=0||state.timeLeft<=0){finish();return}state.locked=false;const question=state.questions[state.index];$('[data-category]').textContent=`${REGIONS[regionIndex()]} · ${question.category}`;$('[data-question]').textContent=question.question;$('[data-options]').innerHTML=question.options.map((option,index)=>`<button class="game-quiz-option" type="button" data-choice="${index}"><strong>${String.fromCharCode(65+index)}.</strong> ${escapeHtml(option.text)}</button>`).join("");$('[data-feedback]').textContent=`Giliran ${names()[activeIndex()]}. Pilih satu jawaban.`;$('[data-feedback]').className="game-message";$('[data-next]').hidden=true;renderHud()}
function recordCategory(category,correct){const row=state.categories[category]||{correct:0,total:0};row.total++;if(correct)row.correct++;state.categories[category]=row}
function answer(index){if(state.locked||state.finished)return;state.locked=true;const question=state.questions[state.index],option=question.options[index],buttons=[...document.querySelectorAll('[data-choice]')],correct=option.sourceIndex===Number(question.answer),active=activeIndex();buttons.forEach(button=>button.disabled=true);state.answered++;recordCategory(question.category,correct);if(correct){state.correct++;state.playerCorrect[active]++;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);const points=300+Math.min(5,state.combo)*40+Math.min(100,state.timeLeft);state.score+=points;buttons[index].classList.add("correct");$('[data-feedback]').textContent=`Benar. +${points} poin. ${question.explanation||""}`;$('[data-feedback]').className="game-message success"}else{state.lives=Math.max(0,state.lives-1);state.combo=0;state.score=Math.max(0,state.score-150);buttons[index].classList.add("wrong");buttons[question.options.findIndex(item=>item.sourceIndex===Number(question.answer))]?.classList.add("correct");$('[data-feedback]').textContent=`Belum tepat. ${question.explanation||""}`;$('[data-feedback]').className="game-message error"}$('[data-next]').hidden=false;renderHud();if(state.lives<=0)$('[data-next]').textContent="Lihat hasil"}
function next(){if(!state.locked)return;state.index++;renderQuestion()}
function finish(){if(state.finished)return;state.finished=true;clearInterval(state.timer);const completed=state.index>=15,won=completed&&state.correct>=state.config.target&&state.lives>0;const duration=Math.max(1,Math.round((Date.now()-state.startAt)/1000));const finalScore=Math.min(10000,state.score+(won?1000:0)+state.lives*100);$('[data-game]').hidden=true;$('[data-result]').hidden=false;$('[data-result-icon]').textContent=won?"🏆":"🧭";$('[data-result-title]').textContent=won?"Ekspedisi Nusantara tuntas!":"Ekspedisi belum mencapai target";$('[data-result-copy]').textContent=`Target ${state.config.target}/15 · hasil ${state.correct}/15 benar · ${state.lives} nyawa tersisa · ${duration} detik.`;$('[data-final-correct]').textContent=`${state.correct}/15`;$('[data-final-combo]').textContent=`${state.bestCombo}×`;$('[data-final-score]').textContent=finalScore.toLocaleString("id-ID");$('[data-category-report]').innerHTML=Object.entries(state.categories).map(([category,row])=>`<article><span>${category}</span><strong>${Math.round(row.correct/row.total*100)}%</strong><small>${row.correct}/${row.total} benar</small></article>`).join("");renderMap();window.dispatchEvent(new CustomEvent("ppn:game-finished",{detail:{gameSlug:"jelajah-nusantara",score:finalScore,accuracy:Math.round(state.correct/15*100),result:won?"won":"lost",mode:state.session.mode,difficulty:state.session.difficulty,levelId:"lima-kawasan",durationSeconds:duration,correctCount:state.correct,questionCount:15,metadata:{clientSessionId:state.id,gameVersion:"2.2.0",target:state.config.target,bestCombo:state.bestCombo,playerCorrect:state.playerCorrect,categories:state.categories,questionSet:state.questionSetName||"Bank soal bawaan"}}}))}
async function start(){try{state.session=requireSession("jelajah-nusantara")||getActivePlayerSession();if(!state.session)return;state.config=configs[state.session.difficulty]||configs.normal;state.lives=state.config.lives;state.timeLeft=state.config.time;await load();$('[data-intro]').hidden=true;$('[data-game]').hidden=false;state.startAt=Date.now();renderQuestion();state.timer=setInterval(()=>{if(state.finished||state.locked)return;state.timeLeft=Math.max(0,state.timeLeft-1);renderHud();if(state.timeLeft<=0)finish()},1000)}catch(error){$('[data-start-error]').textContent=error.message}}
document.addEventListener("DOMContentLoaded",()=>{$('[data-start]').addEventListener("click",start);$('[data-options]').addEventListener("click",event=>{const button=event.target.closest('[data-choice]');if(button)answer(Number(button.dataset.choice))});$('[data-next]').addEventListener("click",next);renderMap();if("serviceWorker" in navigator)navigator.serviceWorker.register("../../service-worker.js",{scope:"../../"}).catch(console.warn)});
