import {getActivePlayerSession,requireSession} from "../../../shared/js/player-session.js";
import {QuestionDeck,createQuizController} from "../../../shared/js/game-quiz.js";
import {cloneBoard,sow,legalMoves,isGameOver,settleBoard} from "./engine.js";
const $=selector=>document.querySelector(selector);const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const state={pits:[Array(7).fill(7),Array(7).fill(7)],stores:[0,0],turn:0,moves:0,busy:false,finished:false,startAt:0,quizCorrect:0,quizTotal:0,quizLimit:6,session:null,deck:null,quiz:null,id:crypto.randomUUID(),last:null};
const difficultySettings={santai:{ai:"random",quizEvery:5,label:"Santai"},normal:{ai:"smart",quizEvery:4,label:"Normal"},ahli:{ai:"expert",quizEvery:3,label:"Ahli"}};
function names(){const players=state.session?.players||["Pemain 1"];return [players[0]||"Pemain 1",state.session?.mode==="coop"?(players[1]||"Pemain 2"):"AI Nusantara"]}
function board(){return {pits:state.pits,stores:state.stores}}
function evaluateMove(player,index,level){const boardCopy=cloneBoard(board());const before=boardCopy.stores[player];const result=sow(boardCopy,player,index);let score=(boardCopy.stores[player]-before)*10+(result.extra?28:0)+result.captured*7;if(level==="expert"&&!result.extra&&!isGameOver(boardCopy)){const oppMoves=legalMoves(boardCopy,1-player);let threat=0;for(const move of oppMoves){const test=cloneBoard(boardCopy);const beforeOpp=test.stores[1-player];const opp=sow(test,1-player,move);threat=Math.max(threat,(test.stores[1-player]-beforeOpp)*8+opp.captured*6+(opp.extra?18:0))}score-=threat*.7}return score+Math.random()*2}
function aiChoice(){const moves=legalMoves(board(),1);const level=difficultySettings[state.session.difficulty]?.ai||"smart";if(level==="random")return moves[Math.floor(Math.random()*moves.length)];return moves.map(index=>({index,score:evaluateMove(1,index,level)})).sort((a,b)=>b.score-a.score)[0].index}
function render(){const playerNames=names();for(let player=0;player<2;player++){const row=$(`[data-row="${player}"]`);row.innerHTML=state.pits[player].map((count,index)=>`<button class="congklak-pit ${!state.busy&&!state.finished&&state.turn===player&&count>0&&!(player===1&&state.session.mode!=="coop")?"selectable":""} ${state.last?.type==="pit"&&state.last.player===player&&state.last.index===index?"last":""}" type="button" data-pit-player="${player}" data-pit-index="${index}" ${state.busy||state.finished||state.turn!==player||count===0||(player===1&&state.session.mode!=="coop")?"disabled":""}><span>${count}</span><span class="seed-dots">${"•".repeat(Math.min(count,12))}</span></button>`).join("")}$('[data-store="0"]').textContent=state.stores[0];$('[data-store="1"]').textContent=state.stores[1];$('[data-store-one]').textContent=state.stores[0];$('[data-store-two]').textContent=state.stores[1];$('[data-move]').textContent=state.moves;$('[data-quiz-score]').textContent=`${state.quizCorrect}/${state.quizTotal}`;$('[data-active-player]').textContent=playerNames[state.turn];$('[data-difficulty]').textContent=difficultySettings[state.session.difficulty]?.label||"Normal";document.querySelectorAll('[data-player-pill]').forEach((pill,index)=>{pill.textContent=playerNames[index];pill.classList.toggle("active",index===state.turn)});$('[data-turn-banner]').textContent=state.busy?"Langkah sedang diproses…":`${playerNames[state.turn]} memilih lubang.`}
function setMessage(message,type=""){$('[data-message]').textContent=message;$('[data-message]').className=`game-message ${type}`.trim()}
async function askQuiz(reason){if(state.quizTotal>=state.quizLimit)return;const playerName=names()[state.turn];const question=state.deck.next();const answer=await state.quiz.ask(question,{playerName,heading:reason});state.quizTotal++;state.deck.record(question,answer.correct);if(answer.correct){state.quizCorrect++;state.stores[state.turn]+=2;setMessage(`Jawaban benar. Bonus 2 biji masuk lumbung ${playerName}.`,"success")}else setMessage("Jawaban belum tepat. Permainan tetap dilanjutkan.","warning");render()}
async function playMove(player,index){if(state.busy||state.finished||player!==state.turn||!state.pits[player][index])return;state.busy=true;state.moves++;state.last=null;render();const result=sow(board(),player,index);state.last=result.last;await sleep(260);render();if(result.captured)setMessage(`${names()[player]} menangkap ${result.captured} biji!`,"success");else if(result.extra)setMessage(`${names()[player]} mendapat giliran tambahan.`,"success");else setMessage("Biji selesai disebarkan.");const settings=difficultySettings[state.session.difficulty]||difficultySettings.normal;if((state.session.mode==="coop"||player===0)&&(result.captured||state.moves%settings.quizEvery===0)&&state.quizTotal<state.quizLimit)await askQuiz(result.captured?"Bonus Tangkapan":"Tantangan Hitung");if(isGameOver(board())){settleBoard(board());render();finish();return}if(!result.extra)state.turn=1-player;state.busy=false;render();if(state.session.mode!=="coop"&&state.turn===1)window.setTimeout(aiTurn,650)}
async function aiTurn(){if(state.finished||state.turn!==1)return;state.busy=true;render();setMessage("AI sedang menghitung langkah…","warning");await sleep(state.session.difficulty==="santai"?900:550);state.busy=false;await playMove(1,aiChoice())}
function finish(){if(state.finished)return;state.finished=true;state.busy=true;const playerNames=names();const winner=state.stores[0]===state.stores[1]?"Seri":state.stores[0]>state.stores[1]?playerNames[0]:playerNames[1];const humanWin=state.session.mode==="coop"||state.stores[0]>=state.stores[1];const duration=Math.max(1,Math.round((Date.now()-state.startAt)/1000));const score=Math.min(10000,Math.max(state.stores[0],state.stores[1])*120+state.quizCorrect*180+(humanWin?1000:0)+Math.max(0,600-duration)*2);$('[data-game]').hidden=true;$('[data-result]').hidden=false;$('[data-result-icon]').textContent=winner==="Seri"?"🤝":"🏆";$('[data-result-title]').textContent=winner==="Seri"?"Permainan berakhir seri":`${winner} menang!`;$('[data-result-copy]').textContent=`${state.moves} langkah · ${state.quizCorrect}/${state.quizTotal} soal benar · ${duration} detik.`;$('[data-final-one]').textContent=state.stores[0];$('[data-final-two]').textContent=state.stores[1];$('[data-final-score]').textContent=score.toLocaleString("id-ID");window.dispatchEvent(new CustomEvent("ppn:game-finished",{detail:{gameSlug:"congklak-cerdas",score,accuracy:state.quizTotal?Math.round(state.quizCorrect/state.quizTotal*100):100,result:humanWin?"won":"lost",mode:state.session.mode,difficulty:state.session.difficulty,levelId:"papan-7",durationSeconds:duration,correctCount:state.quizCorrect,questionCount:state.quizTotal,metadata:{clientSessionId:state.id,gameVersion:"2.2.0",winner,stores:[...state.stores],moves:state.moves,report:state.deck.getReport(),questionSet:state.deck.getSetInfo().name}}}))}
async function start(){try{state.session=requireSession("congklak-cerdas")||getActivePlayerSession();if(!state.session)return;state.deck=await new QuestionDeck("congklak-cerdas", "data/questions.json").load();state.quiz=createQuizController($('[data-quiz-modal]'));$('[data-intro]').hidden=true;$('[data-game]').hidden=false;state.startAt=Date.now();render();setMessage(`${names()[0]} memulai dari sisi bawah.`)}catch(error){$('[data-start-error]').textContent=error.message}}
document.addEventListener("DOMContentLoaded",()=>{$('[data-start]').addEventListener("click",start);$('[data-game]').addEventListener("click",event=>{const pit=event.target.closest('[data-pit-index]');if(pit)playMove(Number(pit.dataset.pitPlayer),Number(pit.dataset.pitIndex))});$('[data-rules]').addEventListener("click",()=>{$('[data-rules-modal]').hidden=false});$('[data-close-rules]').addEventListener("click",()=>{$('[data-rules-modal]').hidden=true});if("serviceWorker" in navigator)navigator.serviceWorker.register("../../service-worker.js",{scope:"../../"}).catch(console.warn)});
