import {getActivePlayerSession,requireSession} from "../../../shared/js/player-session.js";
import {QuestionDeck,createQuizController} from "../../../shared/js/game-quiz.js";
const $=selector=>document.querySelector(selector);
const settings={santai:{rounds:6,lives:6,time:240,label:"Santai"},normal:{rounds:8,lives:4,time:180,label:"Normal"},ahli:{rounds:10,lives:3,time:140,label:"Ahli"}};
const state={session:null,config:null,round:0,target:0,path:[],step:0,lives:4,timeLeft:180,score:0,quizCorrect:0,quizTotal:0,playerScores:[0,0],finished:false,locked:false,timer:null,startAt:0,deck:null,quiz:null,id:crypto.randomUUID(),completed:0};
function names(){const rows=state.session?.players||["Pemain 1"];return [rows[0]||"Pemain 1",state.session?.mode==="coop"?(rows[1]||"Pemain 2"):rows[0]||"Pemain 1"]}
function activeIndex(){return state.session.mode==="coop"?state.round%2:0}
function randomTarget(){let next;do{next=1+Math.floor(Math.random()*10)}while(next===state.target);return next}
function setMessage(text,type=""){$('[data-message]').textContent=text;$('[data-message]').className=`game-message ${type}`.trim()}
function buildRoundList(){$('[data-round-list]').innerHTML=Array.from({length:state.config.rounds},(_,i)=>`<article class="${i<state.completed?"done":""}"><span>Ronde ${i+1}</span><strong>${i<state.completed?"✓":i===state.round?"Aktif":"•"}</strong></article>`).join("")}
function render(){const playerNames=names(),active=activeIndex();$('[data-active-player]').textContent=playerNames[active];$('[data-round]').textContent=`${Math.min(state.round+1,state.config.rounds)}/${state.config.rounds}`;$('[data-lives]').textContent=`${state.lives} ♥`;$('[data-time]').textContent=`${state.timeLeft} dtk`;$('[data-score]').textContent=state.score.toLocaleString("id-ID");$('[data-quiz-score]').textContent=`${state.quizCorrect}/${state.quizTotal}`;$('[data-target]').textContent=state.target||"-";$('[data-progress-bar]').style.width=`${Math.round((state.completed/state.config.rounds)*100)}%`;document.querySelectorAll('[data-player-pill]').forEach((pill,index)=>{pill.textContent=playerNames[index];pill.hidden=index===1&&state.session.mode!=="coop";pill.classList.toggle("active",index===active)});document.querySelectorAll('[data-tile]').forEach(button=>{const number=Number(button.dataset.tile);button.classList.toggle("target",number===state.target);button.classList.toggle("next",number===state.path[state.step]);button.disabled=state.locked||state.finished||number===state.target});buildRoundList()}
function prepareRound(){state.target=randomTarget();state.path=Array.from({length:10},(_,i)=>i+1).filter(n=>n!==state.target);state.step=0;state.locked=false;setMessage(`${names()[activeIndex()]}: tap petak ${state.path.join(" → ")}. Lewati petak ${state.target}.`);render()}
async function completeRound(){state.locked=true;state.completed++;const active=activeIndex();const speedBonus=Math.max(0,state.timeLeft)*2;const roundPoints=350+Math.min(300,speedBonus);state.score+=roundPoints;state.playerScores[active]+=roundPoints;setMessage(`Ronde ${state.round+1} selesai. +${roundPoints} poin.`,"success");render();if((state.round+1)%2===0||state.round===state.config.rounds-1){const question=state.deck.next();const answer=await state.quiz.ask(question,{playerName:names()[active],heading:"Pos Belajar Engklek"});state.quizTotal++;state.deck.record(question,answer.correct);if(answer.correct){state.quizCorrect++;state.score+=250;state.playerScores[active]+=250;state.lives=Math.min(state.config.lives,state.lives+1);setMessage("Jawaban benar. +250 poin dan satu nyawa dipulihkan.","success")}else{state.lives=Math.max(0,state.lives-1);setMessage("Jawaban belum tepat. Satu nyawa berkurang.","warning")}}
 state.round++;if(state.round>=state.config.rounds||state.lives<=0){finish();return}prepareRound()}
function tapTile(number){if(state.locked||state.finished)return;const expected=state.path[state.step];const button=$(`[data-tile="${number}"]`);if(number===expected){button.classList.add("correct");state.step++;const active=activeIndex();state.score+=35;state.playerScores[active]+=35;window.setTimeout(()=>button.classList.remove("correct"),180);if(state.step>=state.path.length)completeRound();else{setMessage(`Tepat. Berikutnya petak ${state.path[state.step]}.`,"success");render()}}else{state.lives=Math.max(0,state.lives-1);button.classList.add("wrong");window.setTimeout(()=>button.classList.remove("wrong"),260);setMessage(`Salah petak. Seharusnya ${expected}. Nyawa berkurang.`,"error");render();if(state.lives<=0)finish()}}
function finish(){if(state.finished)return;state.finished=true;clearInterval(state.timer);state.locked=true;const won=state.completed>=state.config.rounds&&state.lives>0;const duration=Math.max(1,Math.round((Date.now()-state.startAt)/1000));$('[data-game]').hidden=true;$('[data-result]').hidden=false;$('[data-result-icon]').textContent=won?"🏆":"🪨";$('[data-result-title]').textContent=won?"Semua ronde dituntaskan!":"Keseimbangan terhenti";$('[data-result-copy]').textContent=`${state.completed}/${state.config.rounds} ronde · ${state.quizCorrect}/${state.quizTotal} soal benar · ${duration} detik.`;$('[data-final-rounds]').textContent=`${state.completed}/${state.config.rounds}`;$('[data-final-accuracy]').textContent=`${state.quizTotal?Math.round(state.quizCorrect/state.quizTotal*100):100}%`;const finalScore=Math.min(10000,state.score+(won?500:0));$('[data-final-score]').textContent=finalScore.toLocaleString("id-ID");window.dispatchEvent(new CustomEvent("ppn:game-finished",{detail:{gameSlug:"engklek-pintar",score:finalScore,accuracy:state.quizTotal?Math.round(state.quizCorrect/state.quizTotal*100):100,result:won?"won":"lost",mode:state.session.mode,difficulty:state.session.difficulty,levelId:"lapangan-10",durationSeconds:duration,correctCount:state.quizCorrect,questionCount:state.quizTotal,metadata:{clientSessionId:state.id,gameVersion:"2.2.0",completedRounds:state.completed,playerScores:state.playerScores,report:state.deck.getReport(),questionSet:state.deck.getSetInfo().name}}}))}
async function start(){try{state.session=requireSession("engklek-pintar")||getActivePlayerSession();if(!state.session)return;state.config=settings[state.session.difficulty]||settings.normal;state.lives=state.config.lives;state.timeLeft=state.config.time;state.deck=await new QuestionDeck("engklek-pintar", "data/questions.json").load();state.quiz=createQuizController($('[data-quiz-modal]'));$('[data-intro]').hidden=true;$('[data-game]').hidden=false;state.startAt=Date.now();prepareRound();state.timer=setInterval(()=>{if(state.finished||state.locked)return;state.timeLeft=Math.max(0,state.timeLeft-1);render();if(state.timeLeft<=0)finish()},1000)}catch(error){$('[data-start-error]').textContent=error.message}}
document.addEventListener("DOMContentLoaded",()=>{$('[data-start]').addEventListener("click",start);$('[data-board]').addEventListener("click",event=>{const tile=event.target.closest('[data-tile]');if(tile)tapTile(Number(tile.dataset.tile))});window.addEventListener("keydown",event=>{const number=Number(event.key);if(number>=1&&number<=9)tapTile(number);if(event.key==="0")tapTile(10)});if("serviceWorker" in navigator)navigator.serviceWorker.register("../../service-worker.js",{scope:"../../"}).catch(console.warn)});
